version: '3.7'

services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
